name: Deploy Laravel to InfinityFree via FTP

on:
  push:
    branches:
      - main # Akan berjalan otomatis setiap ada push ke branch 'main'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode Terbaru
      uses: actions/checkout@v3

    # (Opsional) Jika kamu ingin GitHub menjalankan composer install otomatis
    # - name: Install Composer Dependencies
    #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # tester
    
    - name: Sinkronisasi ke FTP InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/ # Arahkan ke folder htdocs
        exclude: |
          **/.git*
          **/.git*/**
          node_modules/**
          .env # WAJIB DIKECUALIKAN agar .env di hosting tidak tertimpa
          .env.example